name: MapTowny
version: ${project.version}
main: me.silverwolfg11.maptowny.MapTowny
api-version: 1.16
depend: [ Towny ]
softdepend: [ squaremap, Pl3xMap, dynmap ]
authors: [ Silverwolfg11 ]
description: A web-map addon to support Towny.

commands:
  maptowny:
    description: Command for MapTowny
    permission: maptowny.use

permissions:
  maptowny.admin:
    description: Admin permission for MapTowny
    default: false
    children:
      maptowny.use: true
      maptowny.reload: true
      maptowny.render: true
      maptowny.unrender: true

  maptowny.use:
    description: Permission to use the MapTowny command
    default: op

  maptowny.reload:
    description: Allows access to sub-cmd to reload MapTowny
    default: op

  maptowny.render:
    description: Allows access to sub-cmd to render a town on the web-map.
    default: op

  maptowny.unrender:
    description: Allows access to sub-cmd to unrender a town on the web-map.
    default: op
